icon: ':material-database:'

cit:
  mode: port
  port: 3306

build:
  architectures:
    - amd64
    - aarch64
  variants:
    - tag: "10.11-pkg-latest"
      pkg_name: mariadb1011-server
      containerfile: Containerfile.pkg
      args:
        MARIADB_VERSION: "1011"
        BASE_VERSION: "15.1-latest"
      aliases: ["10.11"]
    - tag: "11.4-pkg-latest"
      pkg_name: mariadb114-server
      containerfile: Containerfile.pkg
      args:
        MARIADB_VERSION: "114"
        BASE_VERSION: "15.1-latest"
      aliases: ["11.4"]
    - tag: "11.8-pkg-latest"
      pkg_name: mariadb118-server
      containerfile: Containerfile.pkg
      args:
        MARIADB_VERSION: "118"
        BASE_VERSION: "15.1-latest"
      aliases: ["11.8"]
    - tag: "12.3-pkg-latest"
      pkg_name: mariadb123-server
      containerfile: Containerfile.pkg
      args:
        MARIADB_VERSION: "123"
        BASE_VERSION: "15.1-latest"
      aliases: ["12.3", "latest", "pkg-latest", "pkg"]
      default: true
